### ISSUE TITLE
 provider.getBlockWithTransactions Can we support it？

### ISSUE THREAD

**Issue by xiaosteel** [ChainStarter/multicall-client.js#1]
provider.getBlockWithTransactions()

**Comment by yuanxxxxxx** [comment]
Already supported in v1.3.2

`const { blockNumber } = await multicallClient.getTransactionReceipt(
      "0xae7332c8a57f1b26c5e181e54d59bcb8c5fe9f42bc1a6b7bbc33197d32978c4e",
      ChainId.BSC
    );`

**Comment by yuanxxxxxx** [comment]
close
